language: ruby
before_install:
  - "test -f ~/.ssh/id_rsa || ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -P ''"
  - chmod 700 ~/.ssh/
  - "chmod 600 ~/.ssh/id_rsa*"
  - 'eval `ssh-agent`'
  - ssh-add ~/.ssh/id_rsa
  - ssh -vv -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa localhost "true"
rvm:
  - 2.0.0
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
